name: Rust

on:
  push:
    branches: [ main ]
    paths: [ '**.rs' ]
  pull_request:
    paths: [ '**.rs' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo test --verbose
